#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */
require __DIR__ . '/vendor/autoload.php';
use Symfony\Component\Dotenv\Dotenv;
$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

if($_ENV['APP_ENV'] === 'development') {
    // comment out the following two lines when deployed to production
    defined('YII_DEBUG') or define('YII_DEBUG', true);
    defined('YII_ENV_DEV') or define('YII_ENV_DEV', true);
    defined('YII_ENV') or define('YII_ENV', 'dev');
    
} else {
    defined('YII_DEBUG') or define('YII_DEBUG', false);
    defined('YII_ENV_DEV') or define('YII_ENV_DEV', false);
    defined('YII_ENV') or define('YII_ENV', 'prod');
}




require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
